### ISSUE TITLE
Document Methodology behind myarbitratord

### ISSUE THREAD

**Issue by grypyrg** [mattlord/myarbitratord#1]
Hi Matt,

Thanks for making this experimental project public.

I would like to understand a bit better how `myarbitratord` works and integrates with group replication.
- When and how does it make decisions?
- What are it's use cases?
- Are there any known cases where it does not work and/or should not be used?

I know I can read the source code, but I think it's important it's documented as well to help understand this better for a wider audience and to avoid false statements to be made.

Would you please document this somehow?

**Comment by mattlord** [comment]
Thanks, Kenny! I agree... I'll add that to my ToDo list. :)

**Comment by mattlord** [comment]
Added some basic info... I'll continue to try and improve it over time. If you have any specific questions let me know and I'll answer them in the README.

**Comment by mattlord** [comment]
Anything else you'd like to see for now? If not then I'll close the ticket and of course build out/improve the README over time. 

Thanks for the great suggestion! Closing for now, can re-open if needed.
